Lab3/Models/ErrorViewModel.cs
namespace Lab3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab3/Models/IContactService.cs
namespace Lab3.Models
{
    public interface IContactService
    {
        void Add(Contact contact);
        void Update(Contact contact);
        void DeleteById(int id);
        Contact? FindById(int id);
        List<Contact> FindAll();
    }
}

Lab3/Models/MemoryContactService.cs
using System.Numerics;
using System.Xml.Linq;

namespace Lab3.Models
{
    public class MemoryContactService : IContactService
    {
        private readonly Dictionary<int, Contact> _contacts =
            new Dictionary<int, Contact>()
            {
                { 1, new Contact() {Id = 1, Name="Adam", Email="adam@wsei.edu.pl", Phone = "11223123" } },
                { 2, new Contact() {Id = 2, Name="Ewa", Email="ewa@wsei.edu.pl", Phone = "51223123" } }
            };
        private int _id = 3;
        public void Add(Contact contact)



        {
            contact.Id = _id++;
            _contacts[contact.Id] = contact;
        }

        public void DeleteById(int id)
        {
            _contacts.Remove(id);
        }

        public List<Contact> FindAll()
        {
            return _contacts.Values.ToList();
        }

        public Contact? FindById(int id)
        {
            return _contacts[id];
        }

        public void Update(Contact contact)
        {
            _contacts[contact.Id] = contact;
        }
    }
}

Lab3/Models/Travel.cs
using System.ComponentModel.DataAnnotations;

namespace Lab3.Models
{
    public class Travel
    {
        public int Id { get; set; }
        public string? Title { get; set; }
        [DataType(DataType.Date)]
        public DateTime BookingDate { get; set; }
        public decimal Price { get; set; }
    }
}

Lab3/Controllers/ContactController.cs
using Lab3.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lab3.Controllers
{
    public class ContactController : Controller
    {
        private readonly IContactService _contactService;
        public ContactController(IContactService contactService)
        {
            _contactService = contactService;
        }
        public IActionResult Index()
        {
            return View(_contactService.FindAll());
        }
        [HttpGet]
        public IActionResult Create() 
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Contact model)
        {
            if (ModelState.IsValid)
            {
                _contactService.Add(model);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Update(int id) 
        {
            return View(_contactService.FindById(id));
        }
        [HttpPost]
        public IActionResult Update(Contact model) 
        {
            if (ModelState.IsValid) 
            {
                _contactService.Update(model);
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Lab3/Controllers/HomeController.cs
using Lab3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Lab3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab3/Views/Contact/Create.cshtml
@model Contact
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Dodaj Kontakt</h1>
<form asp-controller="Contact" asp-action="Create" method="post">
    <label asp-for="Name"></label>
    <input class="form-control" asp-for="Name" />
    <span class="text-danger" asp-validation-for="Name"></span>

    <label asp-for="Email"></label>
    <input class="form-control" asp-for="Email" />
    <span class="text-danger" asp-validation-for="Email"></span>

    <label asp-for="Phone"></label>
    <input class="form-control" asp-for="Phone" />
    <span class="text-danger" asp-validation-for="Phone"></span>

    <label asp-for="Birth"></label>
    <input class="form-control" asp-for="Birth" />
    <span class="text-danger" asp-validation-for="Birth"></span>
    <button type="submit">Dodaj</button>
</form>

Lab3/Views/Contact/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Lab3/Views/Contact/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Lab3/Views/Contact/Index.cshtml
@model List<Contact>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Lista kontaktów</h1>
<a class="btn btn-primary" asp-controller="Contact" asp-action="Create">Dodaj</a>
<table class="table">
    <thead>
        <tr>
            <th>Imię</th>
            <th>Adres e-mail</th>
            <th>Akcje</th>
        </tr>
    </thead>
<tbody>
    @foreach(Contact item in @Model)
        {
            <tr>
                <td>
                    @item.Name
                </td>
                <td>
                    @item.Email
                </td>
                <td>
                    <a asp-action="Update" asp-route-id=@item.Id>Edytuj</a>
                    <a asp-action="Details" asp-route-id=@item.Id>Szczegóły</a>
                    <a asp-action="Delete" asp-route-id=@item.Id>Usuń</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Lab3/Views/Contact/Update.cshtml
@model Contact
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Edytuj Kontakt</h1>
<form asp-controller="Contact" asp-action="Update" method="post">
    <label asp-for="Name"></label>
    <input class="form-control" asp-for="Name" />
    <span class="text-danger" asp-validation-for="Name"></span>

    <label asp-for="Email"></label>
    <input class="form-control" asp-for="Email" />
    <span class="text-danger" asp-validation-for="Email"></span>

    <label asp-for="Phone"></label>
    <input class="form-control" asp-for="Phone" />
    <span class="text-danger" asp-validation-for="Phone"></span>

    <label asp-for="Birth"></label>
    <input class="form-control" asp-for="Birth" />
    <span class="text-danger" asp-validation-for="Birth"></span>
    <button type="submit">Dodaj</button>
</form>

Lab3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #2C2C2C;
            
        }

        header {
            background-color: #2C2C2C;
            color: red;
            padding: 10px;
            text-align: center;
        }

        section {
            max-width: 800px;
            background-color: #fff;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            color: #333;
        }

        p {
            color: #555;
        }

        .cta-button {
            display: inline-block;
            padding: 10px 20px;
            font-size: 16px;
            background-color: #e74c3c;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

        .cta-button:hover {
            background-color: #202020;
        }
    </style>
</head>
<body>

    <header>
        <h1>Travel App</h1>
    </header>

    <section>
        <h1>Witaj w Travel App!</h1>
        <p>Planuj swoje podróże z nami. Odkrywaj nowe miejsca, rezerwuj noclegi i śledź swoje przygody.</p>
        <a href="#" class="cta-button">Zacznij Planować</a>
    </section>

</body>
</html>

Lab3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Kontakty</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Lab3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>